version: '3'
services:
  redirect:
    container_name: redirect
    build: .
    #image: vdbrink/redirect
    ports:
      - "8888:8888"
    environment:
      - REDIRECT_URL=homeassistant://navigate
      - PORT=8888
